# Generated by Django 5.0 on 2024-06-06 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_sale_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopapp.dealer'),
            preserve_default=False,
        ),
    ]
