# Generated by Django 5.0 on 2024-06-07 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_delivery_sale_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='medicine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.medicine'),
        ),
    ]
