# Generated by Django 5.0.6 on 2024-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0019_alter_contact_phone_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
