# Generated by Django 5.0 on 2024-06-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0024_purchaseitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sale'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='sale_items',
        ),
        migrations.AddField(
            model_name='delivery',
            name='sale_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopapp.saleitem'),
            preserve_default=False,
        ),
    ]
