# Generated by Django 5.0 on 2024-06-07 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_remove_sale_medicine_remove_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='shopapp.sale'),
        ),
    ]
