# Generated by Django 5.0 on 2024-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_remove_purchase_customer_remove_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='confirmed',
            field=models.CharField(choices=[('SALE ORDER', 'Sale Order'), ('SALE DELIVERY', 'Sale Delivery')], default='SALE ORDER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.CharField(max_length=20, verbose_name='User Role'),
        ),
    ]
