# Generated by Django 5.0 on 2024-06-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0037_alter_contact_phone_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='tablet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='tablet_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.medicine'),
        ),
    ]
