# Generated by Django 5.0 on 2024-06-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_sale_tablet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
