# Generated by Django 5.0 on 2024-05-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='alternate_phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_acc_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_join',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
    ]
