# Generated by Django 5.0 on 2024-05-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_remove_employee_dob_remove_employee_aadhar_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
