# Generated by Django 5.0 on 2024-06-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0025_alter_delivery_sale_remove_delivery_sale_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='total',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sale'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='sale_items',
        ),
        migrations.AddField(
            model_name='delivery',
            name='sale_items',
            field=models.ManyToManyField(to='shopapp.saleitem'),
        ),
    ]
