# Generated by Django 5.0 on 2024-06-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0029_emaildata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailData',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
