# Generated by Django 5.0 on 2024-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0036_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
