# Generated by Django 5.0 on 2024-06-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_medicine_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='medicine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.tablet'),
        ),
    ]
