# Generated by Django 5.0.6 on 2024-06-13 10:50

import shopapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0017_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(help_text='Enter a 10-digit phone number.', max_length=10, validators=[shopapp.validators.validate_phone_number]),
        ),
    ]
