# Generated by Django 5.0 on 2024-05-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userdetials_dept_userdetials_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetials',
            name='department_name',
        ),
    ]
