# Generated by Django 5.0 on 2024-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userdetials_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetials',
            name='password_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
