# Generated by Django 5.0 on 2024-06-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_sale_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tablet_name',
        ),
    ]
