# Generated by Django 5.0 on 2024-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_lead_opportunity_salesorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
