# Generated by Django 5.0 on 2024-06-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_dealer_price_alter_lead_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
