# Generated by Django 5.0 on 2024-06-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_lead_price_lead_quantity_opportunity_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='tablet_name',
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.dealer')),
            ],
        ),
    ]
