# Generated by Django 5.0 on 2024-06-06 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_remove_purchase_tablets_alter_purchase_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='mail_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='dealer_name',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='tablet_name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablet',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablets', to='shopapp.dealer'),
        ),
    ]
