# Generated by Django 5.0 on 2024-06-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_tablet_remove_dealer_price_remove_dealer_tablet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.tablet'),
        ),
    ]
