# Generated by Django 5.0 on 2024-06-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0023_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
