# Generated by Django 5.0 on 2024-05-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_userdetials_role_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(blank=True),
        ),
    ]
