# Generated by Django 5.0 on 2024-05-27 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetials',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Admin')], null=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('date_of_join', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('alternate_phone_number', models.BigIntegerField(blank=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_acc_number', models.BigIntegerField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('aadhar_no', models.BigIntegerField()),
                ('pan_number', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
