# Generated by Django 5.0.6 on 2024-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_alter_sale_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='confirmed',
            field=models.CharField(choices=[('SALE COUNTER', 'SALE COUNTER'), ('SALE DELIVERY', 'SALE DELIVERY')], default='SALE ORDER', max_length=20),
        ),
    ]
