# Generated by Django 5.0.6 on 2024-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_alter_employee_phone_number_alter_sale_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
