# Generated by Django 5.0 on 2024-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0025_remove_purchaseitem_total_alter_saleitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
