# Generated by Django 5.0 on 2024-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0026_purchaseitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
