# Generated by Django 5.0 on 2024-06-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0027_purchaseitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
