# Generated by Django 5.0 on 2024-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0031_contacts_remove_contact_address_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='tablet_name',
            new_name='tablet',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='confirmed',
            field=models.CharField(choices=[('SALE COUNTER', 'SALE COUNTER'), ('SALE DELIVERY', 'SALE DELIVERY')], default='SALE CONTER', max_length=20),
        ),
    ]
