# Generated by Django 5.0 on 2024-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0033_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%')], default=0),
        ),
    ]
