# Generated by Django 5.0.6 on 2024-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_remove_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_created=10)),
                ('dealer_name', models.CharField(max_length=100)),
                ('tablet_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('comapny_name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('dosageform', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
