# Generated by Django 5.0 on 2024-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_saleitem_total_alter_sale_total_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='sale_items',
            field=models.ManyToManyField(to='shopapp.saleitem'),
        ),
    ]
