# Generated by Django 5.0 on 2024-06-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='Contact',
        ),
    ]
