# Generated by Django 5.0 on 2024-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0002_rename_contactinfo_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('tablet', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
