# Generated by Django 5.0 on 2024-06-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0003_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='email_id',
            new_name='email',
        ),
    ]
