# Generated by Django 5.0 on 2024-06-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0005_category_product_delete_contact_delete_lead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
