# Generated by Django 5.0 on 2024-06-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0008_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
