# Generated by Django 5.0 on 2024-06-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0009_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=250)),
                ('scientific_name', models.CharField(max_length=250)),
            ],
        ),
    ]
