# Generated by Django 5.0 on 2024-06-19 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0011_person_bird_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='name',
        ),
        migrations.AddField(
            model_name='bird',
            name='person',
            field=models.ForeignKey(default=1, help_text='Select the owner of the bird', on_delete=django.db.models.deletion.CASCADE, to='summaapp.person', verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bird',
            name='common_name',
            field=models.CharField(help_text='Enter the common name of the bird', max_length=250, verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='scientific_name',
            field=models.CharField(help_text='Enter the scientific name of the bird', max_length=250, verbose_name='Scientific Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Enter the name of the person', max_length=50, verbose_name="Person's Name"),
        ),
    ]
