# Generated by Django 5.0 on 2024-06-19 06:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0013_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='dealer',
            field=models.CharField(max_length=50, verbose_name='Dealer Name'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.BigIntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='summaapp.purchase', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='tablet_name',
            field=models.CharField(max_length=50, verbose_name='Tablet Name'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total'),
        ),
    ]
