# Generated by Django 5.0 on 2024-06-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaapp', '0015_alter_purchaseitem_price_alter_purchaseitem_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
