# Generated by Django 5.0 on 2024-06-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_remove_dealer_price_remove_dealer_tablet_name_tablet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tablet_name',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.tablet'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='shopapp.purchase')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='tablets',
            field=models.ManyToManyField(through='shopapp.PurchaseItem', to='shopapp.medicine'),
        ),
    ]
