# Generated by Django 5.0 on 2024-06-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_remove_purchase_price_remove_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='tablets',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopapp.purchase'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='tablet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.tablet'),
        ),
    ]
