# Generated by Django 5.0 on 2024-06-06 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_rename_mail_id_dealer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='email',
            new_name='mail_id',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablet',
            name='tablet_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.dealer'),
        ),
    ]
