# Generated by Django 5.0 on 2024-06-07 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_tablet_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.tablet')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sale')),
            ],
        ),
    ]
