# Generated by Django 5.0 on 2024-05-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
