# Generated by Django 5.0 on 2024-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_data_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='salary',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
