# Generated by Django 5.0 on 2024-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_leave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='aadhar_no',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='alternate_phone_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
