# Generated by Django 5.0 on 2024-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='bank_acc_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='bank_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
