# Generated by Django 5.0 on 2024-05-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_data_bank_acc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.DateField(),
        ),
    ]
