# Generated by Django 5.0 on 2024-05-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_payroll_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(help_text='Coming back on ...', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(blank=True, help_text='Add additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(help_text='Leave start date is on ..', null=True, verbose_name='Start Date'),
        ),
    ]
