# Generated by Django 5.0 on 2024-05-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_leave_enddate_alter_leave_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(help_text='coming back on ...', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(blank=True, help_text='add additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(help_text='leave start date is on ..', null=True, verbose_name='Start Date'),
        ),
    ]
