# Generated by Django 5.0 on 2024-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='emp_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
