# Generated by Django 5.0 on 2024-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_employee_data_emp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='emp_code',
            field=models.CharField(max_length=10),
        ),
    ]
