# Generated by Django 5.0 on 2024-06-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_employee_data_emp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_data',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='state',
        ),
        migrations.AddField(
            model_name='employee_data',
            name='current_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='emergency_contact_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='emergency_contact_relationship',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='permenant_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
