# Generated by Django 5.0 on 2024-06-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_remove_employee_data_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='emergency_contact_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
