# Generated by Django 5.0 on 2024-06-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_employee_data_emergency_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='current_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_data',
            name='permenant_address',
            field=models.CharField(max_length=100),
        ),
    ]
