# Generated by Django 5.0 on 2024-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_employee_data_current_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='aadhar_no',
            field=models.CharField(max_length=12),
        ),
    ]
