# Generated by Django 5.0 on 2024-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_alter_employee_data_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='aadhar_no',
            field=models.BigIntegerField(),
        ),
    ]
