# Generated by Django 5.0 on 2024-06-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_alter_employee_data_aadhar_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_data',
            name='alternate_phone_number',
        ),
    ]
